image: karelbemelmans/pipelines-hugo

pipelines:
  default:
    - step:
        script:
          - apk update
          - apk add git
          - mkdir themes && cd themes && git clone https://github.com/digitalcraftsman/hugo-hikari-theme.git && cd ..
          - hugo
          - aws s3 sync --delete public s3://aws-website-blogsuperfuckingcool-1a9mp 