baseurl = "http://blog.superfucking.cool/"
languageCode = "en-us"
title = "Super fucking cool stuff, thoughts and ideas"
disqusShortname = "superfuckingcool-blog"
googleAnalytics = ""
theme = "hugo-hikari-theme"

[params]
	name = "Jeff Sinclair"
	description = "A super fucking cool blog, with some super fucking cool thoughts, ideas and discoveries."
	copyright = "POWERED BY [HUGO](//gohugo.io) - THEME: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme) - © JOHN DOE"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Not fucking cool - Couldn't find shit."
	pageNotFoundSubtitle = "Sorry, but something fucked up and we couldn't find the shit that you asked for. Try again later, maybe. Or fucking don't?"

[params.offcanvas]
	# Menu items
	title = "Hi, I'm Jeff Sinclair"
	bio = "Senior Product Manager; liker of cool shit; buyer of things that I cannot fucking afford. Aiming to get some thoughts down onto paper as I explore various web technologies in my spare time. <br/> The thoughts and language on this blog are my own, and not representative of my current or past employers."
	subscribe = "Subscribe"
	followme = "Follow me on"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/jsinkers"	